// Code generated by MockGen. DO NOT EDIT.
// Source: internal/email/usecase.go

// Package email is a generated GoMock package.
package email

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// SendReport mocks base method.
func (m *MockUseCase) SendReport(ctx context.Context, reportEmail ReportEmail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReport", ctx, reportEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendReport indicates an expected call of SendReport.
func (mr *MockUseCaseMockRecorder) SendReport(ctx, reportEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReport", reflect.TypeOf((*MockUseCase)(nil).SendReport), ctx, reportEmail)
}
